config/routes.rb
Rails.application.routes.draw do
  root "synonyms#index"
  devise_for :users
  resources :synonyms do
    member do
      put "like" => "synonyms#upvote"
      put "unlike" => "synonyms#downvote"
    end
   resources :comments

  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :synonym
  belongs_to :user,optional: true
end

app/models/synonym.rb
class Synonym < ApplicationRecord
    acts_as_votable

	has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
	acts_as_voter
	
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/view.rb
class View < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
before_action: only: [:create, :destroy]
	def create
     @synonym = Synonym.find(params[:synonym_id])
     @comment = @synonym.comments.create(comment_params)
     redirect_to synonym_path(@synonym)
  end
  def destroy
    @synonym = Synonym.find(params[:synonym_id])
    @comment = @synonym.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@synonym), status: 303
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body, :synonym_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	 
  def index
  	if user_signed_in?
  		redirect_to synonyms_path
   end
  end 
end

app/controllers/synonyms_controller.rb
class SynonymsController < ApplicationController
  before_action :set_synonym, only: [ :show, :edit, :update, :destroy, :upvote, :downvote]
  before_action :authenticate_user!
  # GET /synonyms or /synonyms.json
  def index
    @synonyms = Synonym.all
  end
  
  # GET /synonyms/1 or /synonyms/1.json
  def show
  end

  # GET /synonyms/new
  def new
    @synonym = Synonym.new
  end

  # GET /synonyms/1/edit
  def edit
  end

  # POST /synonyms or /synonyms.json
  def create
    @synonym = Synonym.new(synonym_params)

    respond_to do |format|
      if @synonym.save
        format.html { redirect_to synonym_url(@synonym), notice: "Synonym was successfully created." }
        format.json { render :show, status: :created, location: @synonym }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @synonym.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /synonyms/1 or /synonyms/1.json
  def update
    respond_to do |format|
      if @synonym.update(synonym_params)
        format.html { redirect_to synonym_url(@synonym), notice: "Synonym was successfully updated." }
        format.json { render :show, status: :ok, location: @synonym }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @synonym.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /synonyms/1 or /synonyms/1.json
  def destroy
    @synonym.destroy

    respond_to do |format|
      format.html { redirect_to synonyms_url, notice: "Synonym was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  def upvote
    @synonym.upvote_from current_user
    redirect_to synonyms_path
  end

  def downvote
    @synonym.downvote_from current_user
    redirect_to synonyms_path 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_synonym
      @synonym = Synonym.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def synonym_params
      params.require(:synonym).permit(:English_word, :Kannada_meaning,:user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/synonyms_helper.rb
module SynonymsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nom</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
   

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

  <body>
    <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
       
   <div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
  <a class="navbar-brand" href="#">SYNONYMS</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    
       <% if user_signed_in? %>
         <a class="navbar text-right"><%= link_to("Logout",destroy_user_session_path, :method => :delete,class: "btn btn-lg btn-info" ) %> </a>
         <a class="navbar-text navbar-center"> Hello,<%= current_user.email %></a> <br>
         <% else %>
         <%= link_to 'login',new_user_registration_path, class:'btn btn-lg btn-primary' %></p></div>
         <% end %>
      </div>
    </div>
</nav>
       
          
          

    <%= yield %>
  </body>
</html>

app/views/synonyms/_form.html.erb
<%= form_with(model: synonym, local: true) do |form| %>
  <% if synonym.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(synonym.errors.count, "error") %> prohibited this synonym from being saved:</h2>

      <ul>
      <% synonym.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :English_word %>
    <%= form.text_area :English_word %>
  </div>

  <div class="field">
    <%= form.label :Kannada_meaning %>
    <%= form.text_area :Kannada_meaning %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/synonyms/edit.html.erb
<h1>Editing Synonym</h1>

<%= render 'form', synonym: @synonym %>

<%= link_to 'Show', @synonym %> |
<%= link_to 'Back', synonyms_path %>

app/views/synonyms/index.html.erb
<div class="jumbotron">
<h2>        
<table class="table table-sm ">


    <thead class="thead-light">
    <tr >
      
      <th>English word</th></h2>
     <h2> <th>Kannada meaning</th></h2>
      <th colspan="2"></th>
    </tr>
  </thead>
    
      

  <tbody>
    <% @synonyms.each do |synonym| %>
    
      <h2 style="text-align:center;">
      <tr>
        <td><%= synonym.English_word %></td>
        <td><%= synonym.Kannada_meaning %></td>
        
          
      <td><span class ="like_count" <%=synonym.id %>> <%=synonym.get_upvotes.size%> </span>
        <%= link_to 'like', like_synonym_path(synonym),class:"btn btn-success",method: :put  %></td>
        <td><span class ="dislike_count" <%=synonym.id %>> <%=synonym.get_downvotes.size%></span>
          <%= link_to 'unlike', unlike_synonym_path(synonym),class:"btn btn-danger",method: :put  %></td>
        <td><%= link_to 'Show', synonym %></td>
        <td><%= link_to 'Edit', edit_synonym_path(synonym) %></td>
        <td><%= link_to 'Destroy', synonym, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if user_signed_in? %>
<%= link_to 'New Synonym', new_synonym_path %>

<% end %>

app/views/synonyms/new.html.erb
<h1>New Synonym</h1>

<%= render 'form', synonym: @synonym %>

<%= link_to 'Back', synonyms_path %>

app/views/synonyms/show.html.erb
<div class="jumbotron">

<p>
  <strong>English word:</strong>
  <%= @synonym.English_word %>
</p>

<p>
  <strong>Kannada meaning:</strong>
  <%= @synonym.Kannada_meaning %>
</p>

  <% @synonym.comments.each do |comment| %>
<p>
  <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>
<% end %>

<h2>Add a comment:</h2>
<%= form_with model: [ @synonym, @synonym.comments.build ] do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>




<%= link_to 'Edit', edit_synonym_path(@synonym) %> |
<%= link_to 'Back', synonyms_path %>
</div>